[WMS]
INFO=P1

[Network]
LocalPort=8401
#RemoteIP=98.192.38.205
#RemoteIP=10.99.10.141
#RemoteIP=10.117.3.154
RemoteIP=127.0.0.1
RemotePort=8400

[Property]
RE_DRCT_CNT=3  


[DB]
IP=127.0.0.1
#IP=10.99.43.252
#IP=10.117.3.174
DATABASE = HUONS
PORT = 5432
USER = HUONS
USER_PW = HUONS
LOGPATH=.\bin\Debug\ECSCOMALog
FILENAME=IOTASK_